### ISSUE TITLE
Miflora bluetooth sensors

### ISSUE THREAD

**Issue by mvillarejo** [oakbrad/brad-homeassistant-config#58]
Hello 
Thanks for sharing your config files they are really useful.

I'm interested in the flora sensors setup and automations. Ivan see you have 9 of them but there are no associations with 9 BT adapters... How are you connecting them? Based in the doc the can pair with only one at the time.

Thanks!

**Comment by mvillarejo** [comment]
Hello, wondering if you had time to check this, it would be really appreciated.

**Comment by oakbrad** [comment]
The miflora component of HA polls one sensor at a time. So it can poll all 9, it just does them individually. I'm not using BT for anything else on the Pi
