### ISSUE TITLE
Statecards not working

### ISSUE THREAD

**Issue by WinSCaP** [oakbrad/brad-homeassistant-config#63]
I was kindly stealing from your config. But after updating the custom statecards stopped functioning. I changed the following to get it working again:
`    "*.*":
      custom_ui_state_card: custom-ui`
to:
`    "*.*":
      custom_ui_state_card: state-card-custom-ui `

And also commented out the custom_ui_state_card: custom-ui foo both plant.* and light.* 
After updating and setting the local url with frontend: it works again :)

**Comment by oakbrad** [comment]
I suggest everyone use Lovelace at this point :)
